# Generated by Django 3.2.19 on 2023-05-16 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_auto_20230517_0040'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country_Tax',
            new_name='Tax',
        ),
    ]
