# Generated by Django 3.2.19 on 2023-05-13 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0001_initial'),
        ('menu', '0004_alter_category_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category',
            new_name='Categorys',
        ),
    ]
