# Generated by Django 3.2.19 on 2023-05-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_rename_category_categorys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorys',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
