# Generated by Django 3.2.19 on 2023-05-14 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_categorys_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='category_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fooditems', to='menu.categorys'),
        ),
    ]
