# Generated by Django 3.2.19 on 2023-05-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_fooditem_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorys',
            name='category_name',
            field=models.CharField(max_length=50),
        ),
    ]
